### ISSUE TITLE
can't dm

### ISSUE THREAD

**Issue by skidders** [asayers/attendancebot#1]
Few of the user's in slack can't DM attendancebot. or can't find it. How do I fix it?

**Comment by asayers** [comment]
I didn't really expect anyone to try to use `attendancebot`, which is why there was no documentation. I've now added a README. If you run attendancebot as instructed in the README, do you still experience the same problems?

**Comment by skidders** [comment]
Thanks for the reply. Its good now. 

Ralph Simmons
Project Manager, SupportNinja
(512) 843-8874 |We Scale Startups
701 Brazos St. Suite 1616 Austin, TX 78741

On Wed, Sep 14, 2016 5:14 AM, Alex Sayers notifications@github.com
wrote:
I didn't really expect anyone to try to use attendancebot, which is why there
was no documentation. I've now added a README. If you run attendancebot as
instructed in the README, do you still experience the same problems?
